-- MySQL Script generated by MySQL Workbench
-- 12/23/14 13:40:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cms_edu
-- -----------------------------------------------------
-- cms教育系统
DROP SCHEMA IF EXISTS `cms_edu` ;

-- -----------------------------------------------------
-- Schema cms_edu
--
-- cms教育系统
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cms_edu` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cms_edu` ;

-- -----------------------------------------------------
-- Table `cms_edu`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms_edu`.`category` ;

CREATE TABLE IF NOT EXISTS `cms_edu`.`category` (
  `cid` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '分类表主键id',
  `cname` CHAR(20) NOT NULL DEFAULT '' COMMENT '分类名称',
  `pid` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父级id',
  `ctitle` VARCHAR(60) NOT NULL DEFAULT '' COMMENT '分类标题',
  `cdes` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '分类描述',
  `ckeywords` VARCHAR(120) NOT NULL DEFAULT '' COMMENT '关键字',
  `csort` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '分类排序',
  `htmldir` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '静态目录',
  `is_listhtml` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '列表页是否生成静态',
  `is_archtml` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '内容页是否生成静态',
  `is_show` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '是否显示分类,0为不显示，1为显示',
  PRIMARY KEY (`cid`))
ENGINE = MyISAM
COMMENT = '分类表';


-- -----------------------------------------------------
-- Table `cms_edu`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms_edu`.`user` ;

CREATE TABLE IF NOT EXISTS `cms_edu`.`user` (
  `uid` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户表主键id',
  `username` CHAR(20) NOT NULL DEFAULT '' COMMENT '用户名',
  `nickname` VARCHAR(25) NOT NULL DEFAULT '' COMMENT '昵称',
  `password` CHAR(32) NOT NULL DEFAULT '' COMMENT '密码',
  `is_admin` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0为普通用户，1为后台用户',
  `is_lock` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否锁定，0为没有锁定，1为锁定',
  `supper` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '超级管理员，不能被锁定，不能被删除,1为超级管理员，0为普通',
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = MyISAM
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `cms_edu`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms_edu`.`article` ;

CREATE TABLE IF NOT EXISTS `cms_edu`.`article` (
  `aid` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '文章表主键id',
  `title` CHAR(120) NOT NULL DEFAULT '' COMMENT '文章标题',
  `click` MEDIUMINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '点击次数',
  `sendtime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '发表时间',
  `updatetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间，自动更新',
  `thumb` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '缩略图',
  `is_recycle` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0为没有进入的回收站，1为在回收站中',
  `digest` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '文章摘要',
  `attr` SET('图文','推荐','热门','置顶') NULL COMMENT '文章属性',
  `author` CHAR(15) NOT NULL DEFAULT 'admin' COMMENT '作者',
  `category_cid` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所属分类id',
  `user_uid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所属用户id',
  PRIMARY KEY (`aid`),
  INDEX `fk_cmd_article_cms_category_idx` (`category_cid` ASC),
  INDEX `fk_article_user1_idx` (`user_uid` ASC))
ENGINE = MyISAM
COMMENT = '文章表';


-- -----------------------------------------------------
-- Table `cms_edu`.`article_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms_edu`.`article_data` ;

CREATE TABLE IF NOT EXISTS `cms_edu`.`article_data` (
  `keywords` VARCHAR(125) NOT NULL DEFAULT '' COMMENT '关键字',
  `description` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '描述',
  `content` TEXT NULL COMMENT '文章内容',
  `article_aid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所属文章id',
  INDEX `fk_article_data_article1_idx` (`article_aid` ASC))
ENGINE = MyISAM
COMMENT = '文章分离表';


-- -----------------------------------------------------
-- Table `cms_edu`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms_edu`.`tag` ;

CREATE TABLE IF NOT EXISTS `cms_edu`.`tag` (
  `tid` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '标签主键id',
  `tagname` CHAR(26) NOT NULL DEFAULT '' COMMENT '标签名称',
  PRIMARY KEY (`tid`))
ENGINE = MyISAM
COMMENT = '文章标签';


-- -----------------------------------------------------
-- Table `cms_edu`.`article_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms_edu`.`article_tag` ;

CREATE TABLE IF NOT EXISTS `cms_edu`.`article_tag` (
  `article_aid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所属文章id',
  `tag_tid` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所属标签id',
  `category_cid` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所属分类id',
  INDEX `fk_article_tag_article1_idx` (`article_aid` ASC),
  INDEX `fk_article_tag_tag1_idx` (`tag_tid` ASC),
  INDEX `fk_article_tag_category1_idx` (`category_cid` ASC))
ENGINE = MyISAM
COMMENT = '文章与标签关联表';


-- -----------------------------------------------------
-- Table `cms_edu`.`config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms_edu`.`config` ;

CREATE TABLE IF NOT EXISTS `cms_edu`.`config` (
  `coid` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(15) NOT NULL DEFAULT '' COMMENT '配置项名称',
  `value` VARCHAR(70) NOT NULL DEFAULT '' COMMENT '配置值',
  `title` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '配置项标题',
  `des` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '配置项详细描述',
  `type_id` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配置项类型id，相同类型id相同',
  PRIMARY KEY (`coid`))
ENGINE = MyISAM
COMMENT = '站点配置';


-- -----------------------------------------------------
-- Table `cms_edu`.`flink`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms_edu`.`flink` ;

CREATE TABLE IF NOT EXISTS `cms_edu`.`flink` (
  `fid` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '友情链接主键id',
  `fname` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '友情链接名称',
  `msg` VARCHAR(150) NOT NULL DEFAULT '' COMMENT '友情链接描述',
  `addtime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '添加时间',
  `sort` SMALLINT UNSIGNED NOT NULL DEFAULT 100 COMMENT '排序',
  `logo` VARCHAR(80) NOT NULL DEFAULT '' COMMENT '友情链接Logo',
  `url` VARCHAR(75) NOT NULL DEFAULT '' COMMENT '友情链接地址',
  `is_show` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '0为不显示，1为默认为显示',
  PRIMARY KEY (`fid`))
ENGINE = MyISAM
COMMENT = '友情链接';


-- -----------------------------------------------------
-- Table `cms_edu`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cms_edu`.`comment` ;

CREATE TABLE IF NOT EXISTS `cms_edu`.`comment` (
  `coid` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '评论主键id',
  `pid` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父级id',
  `comcon` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '评论内容',
  `addtime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '发表时间',
  `user_uid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所属用户uid',
  `article_aid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '所属文章aid',
  PRIMARY KEY (`coid`),
  INDEX `fk_comment_user1_idx` (`user_uid` ASC),
  INDEX `fk_comment_article1_idx` (`article_aid` ASC))
ENGINE = MyISAM
COMMENT = '文章评论表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
